# @package _group_ 
# https://github.com/advimman/lama/blob/6bb704738d4e791106d8e87099d80831999901fc/configs/training/generator/ffc_resnet_075.yaml
kind: ffc_resnet
input_nc: 4
output_nc: 3
ngf: 64
n_downsampling: 3
n_blocks: 9
add_out_act: sigmoid

init_conv_kwargs:
  ratio_gin: 0
  ratio_gout: 0
  enable_lfu: False

downsample_conv_kwargs:
  ratio_gin: 0
  ratio_gout: 0
  enable_lfu: False

resnet_conv_kwargs:
  ratio_gin: 0.75
  ratio_gout: 0.75
  enable_lfu: False